targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "Unlicense", "Zlib", "MPL-2.0", "ISC", "BSD-3-Clause", "OpenSSL", "Unicode-DFS-2016" ]
exceptions = []

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "rustls-webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [    
    # Blocked on cookie-store updating idna
    { name = "idna", version = "0.2.3" },
    { name = "idna", version = "0.3.0" },
    
    { name = "syn", version = "1.0.109" },
    { name = "socket2", version = "0.4.9" },
]

deny = [    
    # The general idea seems unsound, and the current version does contain UB.
    # https://github.com/Kimundi/owning-ref-rs/issues/71
    { name = "owning_ref", version = "*" },
    
    # It's a crate only intended for testing; people insist on using it for some reason.
    # https://crates.io/crates/markup5ever_rcdom/0.1.0
    { name = "markup5ever_rcdom", version = "0.1.0" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = []
